
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
after_success: npm run coverage
before_script:
  - psql -c 'create database teamwork;' -U postgres
  - psql -c "CREATE USER david WITH PASSWORD 'password';" -U postgres
services:
  - postgresql