
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
    - "test"
after_success: npm run coverage
before_script:
  psql -c 'create database travis_ci_test;' -U postgres
  psql -u postgres  -d travis_ci_test -a -f start.sql
  
services:
  - postgresql