
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
after_success: npm run coverage
before_script:
  - psql -c "CREATE ROLE david WITH PASSWORD 'password';" -U postgres
  - psql -c "ALTER ROLE david CREATEDB;" -U postgres
  - psql -c 'create database teamwork;' -U david
  
services:
  - postgresql